# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charityname', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('paypal_email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Charity')),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('A', 'Added'), ('U', 'Updated'), ('D', 'Deleted')], default='A', max_length=1)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Admin')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Charity')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=80, unique=True)),
                ('charity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Charity')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Member')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to='sharejarapp.Member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Team')),
            ],
        ),
        migrations.AddField(
            model_name='invite',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Member'),
        ),
        migrations.AddField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Team'),
        ),
        migrations.AddField(
            model_name='donation',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Member'),
        ),
        migrations.AddField(
            model_name='donation',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Team'),
        ),
        migrations.AddField(
            model_name='balances',
            name='charity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Charity'),
        ),
        migrations.AddField(
            model_name='balances',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Member'),
        ),
        migrations.AddField(
            model_name='balances',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='balances',
            unique_together=set([('member', 'team')]),
        ),
    ]
