# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharejarapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balances',
            old_name='currbalance_num',
            new_name='balance',
        ),
    ]
