# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-24 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sharejarapp', '0002_auto_20161003_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charityname', models.CharField(default='DefaultCharityName', max_length=80, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('paypal_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('A', 'Added'), ('U', 'Updated'), ('D', 'Deleted')], default='A', max_length=1)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Admin')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Charity')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='balances',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='balances',
            name='charity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Charity'),
        ),
        migrations.AddField(
            model_name='balances',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Member'),
        ),
        migrations.RemoveField(
            model_name='balances',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='balances',
            unique_together=set([('member', 'charity')]),
        ),
    ]
