# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharejarapp', '0003_auto_20161024_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=80, unique=True)),
                ('leader', models.CharField(default='Unknown', max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='charity',
            name='charityname',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='charity',
            name='paypal_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Team'),
        ),
    ]
