# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-28 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharejarapp', '0004_auto_20161128_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Member'),
        ),
    ]
