# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharejarapp', '0005_auto_20161128_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Charity')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Member')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='invite',
            name='code',
        ),
        migrations.RemoveField(
            model_name='invite',
            name='email',
        ),
        migrations.AddField(
            model_name='invite',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Member'),
        ),
    ]
