# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharejarapp', '0006_auto_20161129_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemberlist',
            name='member',
        ),
        migrations.AddField(
            model_name='balances',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='charity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sharejarapp.Charity'),
        ),
        migrations.AddField(
            model_name='teammemberlist',
            name='members',
            field=models.ManyToManyField(to='sharejarapp.Member'),
        ),
    ]
