# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharejarapp', '0007_auto_20161130_0701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='balances',
            unique_together=set([('member', 'team')]),
        ),
    ]
